### ISSUE TITLE
GUI - Menu - Minimap

### ISSUE THREAD

**Issue by GuyomT** [LucasTesnier/ZAAAAAAAAAAAAppy#31]
Create a minimap displaying the total map with simplified view

**Comment by osvegn** [comment]
Minimap()
~Minimap()
void display()
void addPlayer(const std::string &name, const sf::Vector2f &position)
void removePlayer(const std::string &name)
void setMapSize(const sf::Vector2f &size)
void switchSize()

std::vector<std::tuple<std::string, sf::Vector2f>> playerList
sf::Sprite minimap
sf::ConvexShape map

**Comment by osvegn** [comment]
the position must depend on the menu below
