### ISSUE TITLE
GUI - Utility - LibAnimation

### ISSUE THREAD

**Issue by GuyomT** [LucasTesnier/ZAAAAAAAAAAAAppy#91]
An animation library to animate a sprite?

`Animation(sf::Sprite& sprite) { 
       this->_sprite = &sprite;
       totalProgress = 0.0;
     }`

**Comment by osvegn** [comment]
Edit this issue to add usefull variable for the class as follow:
-`documentation: what is the utility of this variable`
-`his type and his name`

The sprite to be display on the screen
sf::Sprite _sprite
